# Generated by Django 5.2.5 on 2025-08-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('maths_10', models.IntegerField(max_length=3)),
                ('science_10', models.IntegerField(max_length=3)),
                ('english_10', models.IntegerField(max_length=3)),
                ('social_science_10', models.IntegerField(max_length=3)),
                ('hindi_10', models.IntegerField(max_length=3)),
                ('Pe_10', models.IntegerField(max_length=3)),
                ('total_10', models.IntegerField(max_length=3)),
                ('maths_12', models.IntegerField(max_length=3)),
                ('physics_12', models.IntegerField(max_length=3)),
                ('chemistry_12', models.IntegerField(max_length=3)),
                ('english_12', models.IntegerField(max_length=3)),
                ('computer_science_12', models.IntegerField(max_length=3)),
                ('total_12', models.IntegerField(max_length=3)),
            ],
        ),
    ]
