# Generated by Django 5.2.5 on 2025-08-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='Pe_10',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marks',
            name='chemistry_12',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marks',
            name='computer_science_12',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marks',
            name='english_10',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marks',
            name='english_12',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marks',
            name='hindi_10',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marks',
            name='maths_10',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marks',
            name='maths_12',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marks',
            name='physics_12',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marks',
            name='science_10',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marks',
            name='social_science_10',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marks',
            name='total_10',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marks',
            name='total_12',
            field=models.IntegerField(),
        ),
    ]
