# Generated by Django 5.2.5 on 2025-08-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_marks_pe_10_alter_marks_chemistry_12_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='Pe_10',
            new_name='pe_10',
        ),
    ]
