# Generated by Django 5.2.5 on 2025-08-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_pe_10_marks_pe_10'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='computer_science_12',
            new_name='pe_12',
        ),
    ]
