# Generated by Django 5.2.5 on 2025-08-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_feereceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feereceipt',
            name='receipt_image',
            field=models.ImageField(upload_to='receipts/'),
        ),
    ]
