# Generated by Django 5.2.5 on 2025-08-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_feereceipt_receipt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='message_images/'),
        ),
    ]
